environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"

build: off

install:
  # Stockfish
  - ps: Start-FileDownload "https://stockfishchess.org/files/stockfish-11-win.zip"
  - 7z e stockfish-11-win.zip stockfish-11-win/Windows/*.exe
  - ren stockfish_11_x64_popcnt.exe stockfish.exe
  - set PATH=%cd%;%PATH%

test_script:
  - "%PYTHON%\\python.exe test.py -vv"
