environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"

build: off

install:
  # Stockfish
  - ps: Start-FileDownload "https://stockfishchess.org/files/stockfish-10-win.zip"
  - 7z e stockfish-10-win.zip
  - cp stockfish-10-win/Windows/stockfish_10_x64_popcnt.exe stockfish.exe
  - "set PATH=%cd%;%PATH%"

test_script:
  - "%PYTHON%\\python.exe test.py -vv"
